{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "30ac218d",
   "metadata": {},
   "outputs": [],
   "source": [
    "%run ../notebooks/Utilities.ipynb"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "0e95a9a9",
   "metadata": {},
   "outputs": [],
   "source": [
    "table_names = ['hired_employees','departments','jobs']\n",
    "checkpoint_date = pd.Timestamp.now() #for this example I assume that the backup restore is the same day as the backup creation.\n",
    "database_schema = 'DE'\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "881e4316",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Connect to  PostgreSQL\n",
    "DATABASE_URL = 'postgresql+psycopg2://user:password@localhost:5432/DE_Project'\n",
    "engine = create_engine(DATABASE_URL)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "2b9b38e0",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Set up logging\n",
    "logging.basicConfig(filename='../logs/restore.log', level=logging.INFO, format='%(asctime)s %(message)s')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "f0baca03",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Extract the year, month and day from the checkpoint_date\n",
    "year =  checkpoint_date.year\n",
    "month = checkpoint_date.month\n",
    "day = checkpoint_date.day"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "35098a35",
   "metadata": {},
   "outputs": [],
   "source": [
    "for table_name in table_names: \n",
    "    try:\n",
    "        logging.info(f\"Starting restore for table: {table_name} with backup date: {checkpoint_date.strftime('%Y%m%d')}\")\n",
    "        df = restore_table_from_avro(table_name,year,month,day,logging)\n",
    "        logging.info (f'Restored the table {table_name} as a Dataframe succesfully')\n",
    "    except Exception as e:\n",
    "        logging.error(f\"Failed to restore table: {str(e)}\")\n",
    "    \n",
    "    #Insert the data into the table on the Postgre Database\n",
    "    try:\n",
    "        write_to_PostgreSQL (df,table_name,database_schema,engine)\n",
    "        logging.info(f\"Restored procedure completed successfully for table: {table_name} on the Postgre Database\")\n",
    "    except Exception as e:\n",
    "        logging.error(f\"Error during restore: {str(e)}\")\n",
    "        raise e    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "caf8854d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
